changed deploy action on push; added action for manual deploy by tag

diff --git a/.github/workflows/deploy_with_tag.yml b/.github/workflows/deploy_with_tag.yml
--- a/.github/workflows/deploy_with_tag.yml
+++ b/.github/workflows/deploy_with_tag.yml
@@ -1,9 +1,11 @@
-name: Deploy to wattbrews.me
+name: Deploy to wattbrews.me with tag
 
 on:
-  push:
-    branches:
-      - master
+  workflow_dispatch:
+    inputs:
+      tag:
+        description: 'Tag to deploy'
+        required: true
 
 jobs:
   build:
@@ -13,6 +15,16 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.tag }}
+
+      - name: Check if tag exists
+        run: |
+          git fetch --all --tags
+          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
+            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
+            exit 1
+          fi
 
       - name: Prepare configuration file
         run: |
